version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code has alive
          command: |
            ls -al
            echo '^^^ hoge fuga ^^^'
      - run:
          name: Install library
          command: |
            sudo apt-get update
            sudo apt-get install -y graphicsmagick
      - restore_cache:
          name: Restore bundle cache
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle check --path vendor/bundle ||  bundle install --without development --path vendor/bundle --jobs 4 --retry 3
      - save_cache:
          name: Store bundle cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: RSpec
          command: |
            bundle exec rspec \
              --profile 10 \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: /tmp/test-results
